# +------------+--------------+-----------------------------------------------------------+
# |   Author   |     Date     |                         Changed                           |
# +------------+--------------+-----------------------------------------------------------+
# | Qt5 UI gen |  2022/09/29  | Auto-generated (from resources/dbmgr_mainwindow.ui)       |
# +------------+--------------+-----------------------------------------------------------+


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 578)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.baseVert = QtWidgets.QVBoxLayout()
        self.baseVert.setObjectName("baseVert")
        self.upperTimeSearchHori = QtWidgets.QHBoxLayout()
        self.upperTimeSearchHori.setObjectName("upperTimeSearchHori")
        self.timeSearchEnableChkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.timeSearchEnableChkBox.setFont(font)
        self.timeSearchEnableChkBox.setObjectName("timeSearchEnableChkBox")
        self.upperTimeSearchHori.addWidget(self.timeSearchEnableChkBox)
        self.timeSearchFromEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.timeSearchFromEdit.setFont(font)
        self.timeSearchFromEdit.setObjectName("timeSearchFromEdit")
        self.upperTimeSearchHori.addWidget(self.timeSearchFromEdit)
        self.timeSearchFromLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.timeSearchFromLbl.setFont(font)
        self.timeSearchFromLbl.setObjectName("timeSearchFromLbl")
        self.upperTimeSearchHori.addWidget(self.timeSearchFromLbl)
        self.timeSearchToEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.timeSearchToEdit.setFont(font)
        self.timeSearchToEdit.setObjectName("timeSearchToEdit")
        self.upperTimeSearchHori.addWidget(self.timeSearchToEdit)
        self.timeSearchToLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.timeSearchToLbl.setFont(font)
        self.timeSearchToLbl.setObjectName("timeSearchToLbl")
        self.upperTimeSearchHori.addWidget(self.timeSearchToLbl)
        self.baseVert.addLayout(self.upperTimeSearchHori)
        self.upperNameSearchHori = QtWidgets.QHBoxLayout()
        self.upperNameSearchHori.setObjectName("upperNameSearchHori")
        self.nameSearchEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.nameSearchEdit.setFont(font)
        self.nameSearchEdit.setObjectName("nameSearchEdit")
        self.upperNameSearchHori.addWidget(self.nameSearchEdit)
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.searchBtn.setFont(font)
        self.searchBtn.setObjectName("searchBtn")
        self.upperNameSearchHori.addWidget(self.searchBtn)
        self.baseVert.addLayout(self.upperNameSearchHori)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.baseVert.addWidget(self.tableView)
        self.lowerExportGraphHori = QtWidgets.QHBoxLayout()
        self.lowerExportGraphHori.setObjectName("lowerExportGraphHori")
        self.graphBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.graphBtn.setFont(font)
        self.graphBtn.setObjectName("graphBtn")
        self.lowerExportGraphHori.addWidget(self.graphBtn)
        self.exportBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.exportBtn.setFont(font)
        self.exportBtn.setObjectName("exportBtn")
        self.lowerExportGraphHori.addWidget(self.exportBtn)
        self.baseVert.addLayout(self.lowerExportGraphHori)
        self.verticalLayout_2.addLayout(self.baseVert)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "온도미쁨 - 데이터베이스 관리 도구"))
        self.timeSearchEnableChkBox.setText(_translate("MainWindow", "시간 검색"))
        self.timeSearchFromLbl.setText(_translate("MainWindow", "부터"))
        self.timeSearchToLbl.setText(_translate("MainWindow", "까지"))
        self.searchBtn.setText(_translate("MainWindow", "검색"))
        self.graphBtn.setText(_translate("MainWindow", "그래프"))
        self.exportBtn.setText(_translate("MainWindow", "액셀 파일로 내보내기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
